config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :registrations
  resources :sessions, only: [:new, :create]
  resources :users, only: [:show, :edit, :update]
  resources :books, only: [:index, :new, :show, :update]
  resources :borrows, only: [] do
    member do
      post :create_borrow
      delete :close_borrow
    end
  end
  delete 'logout' => 'sessions#destroy', as: :logout
  match '*unmatched', to: 'application#not_found_method', via: :all
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :require_login, only: %i[ create edit destroy update ]
  # GET /books or /books.json
  def index
    if params[:search]
      @books = Book.where("#{params[:filter]} LIKE ?", "%#{params[:search].downcase}%")
    else
      @books = Book.all
    end
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    redirect_to books_path, alert: 'Vous ne possédez pas les autorisations pour créer un livre.'
  end

  # GET /books/1/edit
  def edit
    redirect_to books_path, alert: 'Vous ne possédez pas les autorisations pour éditer un livre.'
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find_by(id: params[:id])
    
      if @book.present?
        # do your stuff
      else
        content_not_found
      end
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :publish_year, :number_borrow)
    end
    def require_login
      unless logged_in?
        redirect_to new_session_path, alert: "Vous devez être connecté pour effectuer une action sur un livre."
      end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
<div class="row">
  <div class="col-4 relative-pos">
    <%= image_tag 'book.png', alt: 'Kindle-on-Rails, a book', class: 's-image' %>
  </div>
  <div class="col-8">
    <div>
      <h1><%= book.title %></h1>
    </div>
  <div>
      <h5><i><%= book.author %> - <%= book.publish_year %></i></h5>
    </div>
<div>
      <strong>Nombre d'emprunt:</strong>
      <%= book.number_borrow %>
    </div>
  
    </div>
  </div>
</div>

app/views/books/_book_show.html.erb
<div id="<%= dom_id @book %>">
<% is_borrow = Borrow.find_by(book_id:@book.id,ended_at:nil)%>
<div class="row">
  <div class="col-4 relative-pos">
    <%= image_tag 'book.png', alt: 'Kindle-on-Rails, a book', class: 's-image' %>
  </div>
  <div class="col-5">
    <div>
      <h1><%= @book.title %></h1>
    </div>
  <div>
      <h5><i><%= @book.author %> - <%= @book.publish_year %></i></h5>
    </div>
<div>
      <strong>Nombre d'emprunt:</strong>
      <%= @book.number_borrow %>
    </div>

    </div>
    <div class="col-3">
      <div class="card">
        <div class="card-body">
            <% if(is_borrow) %>
              <h6 class="text-danger">Ce livre est en cours d'emprunt depuis le <%= is_borrow.started_at.strftime("%d/%m/%Y") %>.</h6>
              <p class="text-danger">Vous devez attendre le retour de ce livre pour pouvoir l'emprunter.</p>
              <% if(current_user && current_user.id == is_borrow.user_id)%>
              <%= form_with(url: close_borrow_borrow_path(@book, return_to: request.path), method: :delete, class:"full-width") do |form| %>
                <%= form.submit "Rendre ce chef d'oeuvre", class:"btn btn-danger" %>
              <%end%>
              <%end%>
            <%else%>
              <h6 class="text-success">Ce livre est disponible.</h6>
              <p class="text-success">Empruntez-le maintenant!</p>
              <%= form_with(url: create_borrow_borrow_path(@book), method: :post) do |form| %>
                <%= form.submit "Emprunter ce chef d'oeuvre", class:"btn btn-success" %>
              <%end%>
            <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :publish_year, style: "display: block" %>
    <%= form.number_field :publish_year %>
  </div>

  <div>
    <%= form.label :number_borrow, style: "display: block" %>
    <%= form.number_field :number_borrow %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tous nos livres</h1>
<hr>
<div id="books" class="row">
<% @books.each do |book| %>
<% is_borrow = Borrow.find_by(book_id:book.id,ended_at:nil)%>
  <div class="col-6">
    <%= link_to book, class:"no-decoration" do %>
    <div class="card <%= (is_borrow) ? "is_borrow" : ""%> book-widget">
      <div class="card-body">
          <%= render book %>
        </div>
        
        <% if(is_borrow) %>
      <div class="card-footer">
        <span class="text-danger">
              <% if(current_user && current_user.id == is_borrow.user_id)%>
                <%= form_with(url: close_borrow_borrow_path(book, return_to: request.path), method: :delete) do |form| %>
                  <%= form.submit "Rendre ce livre", class:"btn btn-danger on-top" %>
                <%end%>
              <%else%>
              Indisponible
              <%end%>
        </span>
      </div>
      <%end%>
      </div>
    <%end%>
    </div>
  <% end %>  
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: 'book_show', locals: { product: @book } %>

<div>
  <%= link_to "Back to books", books_path, class:"btn btn-danger" %>
</div>